# Generated by Django 4.1.7 on 2023-09-20 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0003_employeerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerecord',
            name='device',
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='allocation_condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='allocation_end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='allocation_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='asset_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='device_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='return_condition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
